
POST http://localhost:7777/api/cats
Content-Type: application/json

{
  "name": "Peachy",
  "pattern": "tortoise",
  "colors": ["black", "white", "orange"],
  "age": 10,
  "imageUrl": "https://www.pexels.com/sv-se/foto/djur-husdjur-sot-kattunge-104827/"
}


### GET ALL CATS
GET http://localhost:7777/api/visits

### CREATE CAT
POST http://localhost:7777/api/visits
Content-Type: application/json

{
"name": "Karin",
"date": "2025-04-29T12:30:00.000",
"cat": "6810916c18be603c5c325e6b"
}